CREATE TABLE IF NOT EXISTS APM_APP_HITS (
           UUID VARCHAR(500) NOT NULL,
           APP_NAME VARCHAR(200) NOT NULL,
           VERSION VARCHAR(50),
           CONTEXT VARCHAR(256) NOT NULL,
           USER_ID VARCHAR(50) NOT NULL,
           TENANT_ID INTEGER,
           HIT_TIME TIMESTAMP NOT NULL,
           FOREIGN KEY (TENANT_ID,USER_ID) REFERENCES APM_SUBSCRIBER(TENANT_ID,USER_ID),
           PRIMARY KEY (APP_NAME, VERSION, USER_ID, TENANT_ID, HIT_TIME)
)ENGINE INNODB;

CREATE TABLE IF NOT EXISTS APM_EXTERNAL_STORES (
           APP_STORE_ID INTEGER AUTO_INCREMENT,
           APP_ID INTEGER,
           STORE_ID VARCHAR(255) NOT NULL,
           FOREIGN KEY(APP_ID) REFERENCES APM_APP(APP_ID) ON UPDATE CASCADE ON DELETE CASCADE,
           PRIMARY KEY (APP_STORE_ID)
)ENGINE INNODB;
