# Copyright (c) 2015, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
classes:
  - wso2bps
wso2::pack_filename: "%{::product_name}-%{::product_version}.zip"
wso2::pack_extracted_dir: "%{::product_name}-%{::product_version}"

wso2::template_list :
        - repository/conf/datasources/activiti-datasources.xml
        - repository/conf/datasources/bps-datasources.xml
        - repository/conf/bps.xml
        - repository/conf/humantask.xml
        - repository/conf/jndi.properties

wso2::service_name: wso2bps
wso2::hostname : bps.wso2.com

#wso2::file_list :
#  - repository/components/lib/mysql-connector-java-5.1.36.jar

#wso2::registry_mounts:
#  wso2_config_db:
#    path: /_system/config
#    target_path: /_system/config
#    read_only: true
#    registry_root: /
#    enable_cache: true
#
#  wso2_gov_db:
#    path: /_system/gov
#    target_path: /_system/gov
#    read_only: true
#    registry_root: /
#    enable_cache: true

wso2::so_timeout: 600000
wso2::connection_timeout: 600000
wso2::mex_timeout: 600000
wso2::external_service_timeout: 600000
wso2::max_connections_per_host: 350
wso2::max_total_connections: 400
wso2::ode_scheduler_thread_pool_size: 50
wso2::scheduler_config_max_thread_pool_size: 50
wso2::enable_humantask_caching: false

#wso2::usermgt_datasource: wso2user_db
#
#wso2::master_datasources :
#  wso2_config_db :
#    name : WSO2_CONFIG_DB
#    description : The datasource used for config registry
#    driver_class_name : com.mysql.jdbc.Driver
#    url : jdbc:mysql://192.168.100.1:3306/WSO2REG_DB?autoReconnect=true
#    username : root
#    password : root
#    #securevault :
#    jndi_config : jdbc/WSO2_CONFIG_DB
#    max_active : "%{hiera('wso2::datasources::common::max_active')}"
#    max_wait : "%{hiera('wso2::datasources::common::max_wait')}"
#    test_on_borrow : "%{hiera('wso2::datasources::common::test_on_borrow')}"
#    default_auto_commit : "%{hiera('wso2::datasources::common::default_auto_commit')}"
#    validation_query : "%{hiera('wso2::datasources::mysql::validation_query')}"
#    validation_interval : "%{hiera('wso2::datasources::common::validation_interval')}"
#
#  wso2_gov_db :
#    name : WSO2_GOV_DB
#    description : The datasource used for gov registry
#    driver_class_name : com.mysql.jdbc.Driver
#    url : jdbc:mysql://192.168.100.1:3306/WSO2REG_DB?autoReconnect=true
#    username : root
#    password : root
#    #securevault : false
#    jndi_config : jdbc/WSO2_GOV_DB
#    max_active : "%{hiera('wso2::datasources::common::max_active')}"
#    max_wait : "%{hiera('wso2::datasources::common::max_wait')}"
#    test_on_borrow : "%{hiera('wso2::datasources::common::test_on_borrow')}"
#    validation_query : "%{hiera('wso2::datasources::mysql::validation_query')}"
#    default_auto_commit : "%{hiera('wso2::datasources::common::default_auto_commit')}"
#    validation_interval : "%{hiera('wso2::datasources::common::validation_interval')}"
#
#  wso2user_db :
#    name : WSO2USER_DB
#    description : The datasource is used for user mangement and userstore
#    driver_class_name : com.mysql.jdbc.Driver
#    url : jdbc:mysql://192.168.100.1:3306/WSO2USER_DB?autoReconnect=true
#    username : root
#    password : root
#    #securevault :
#    jndi_config : jdbc/WSO2USER_DB
#    max_active : "%{hiera('wso2::datasources::common::max_active')}"
#    max_wait : "%{hiera('wso2::datasources::common::max_wait')}"
#    test_on_borrow : "%{hiera('wso2::datasources::common::test_on_borrow')}"
#    default_auto_commit : "%{hiera('wso2::datasources::common::default_auto_commit')}"
#    validation_query : "%{hiera('wso2::datasources::mysql::validation_query')}"
#    validation_interval : "%{hiera('wso2::datasources::common::validation_interval')}"

wso2::activiti_datasources :
  activiti_db :
    name : ACTIVITI_DB
    description : The datasource used for activiti engine
    driver_class_name : org.h2.Driver
    url : jdbc:h2:repository/database/activiti;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000
    username : wso2carbon
    password : wso2carbon
    #securevault :
    jndi_config : jdbc/ActivitiDB
    max_active : "%{hiera('wso2::datasources::common::max_active')}"
    max_wait : "%{hiera('wso2::datasources::common::max_wait')}"
    test_on_borrow : "%{hiera('wso2::datasources::common::test_on_borrow')}"
    default_auto_commit : "%{hiera('wso2::datasources::common::default_auto_commit')}"
    validation_query : "%{hiera('wso2::datasources::mysql::validation_query')}"
    validation_interval : "%{hiera('wso2::datasources::common::validation_interval')}"

wso2::bps_datasources :
  bps_ds :
    name : BPS_DS
    description : The datasource used for bps
    driver_class_name : org.h2.Driver
    url : jdbc:h2:file:repository/database/jpadb;DB_CLOSE_ON_EXIT=FALSE;MVCC=TRUE
    username : wso2carbon
    password : wso2carbon
    #securevault :
    jndi_config : bpsds
    max_active : "%{hiera('wso2::datasources::common::max_active')}"
    max_wait : "%{hiera('wso2::datasources::common::max_wait')}"
    test_on_borrow : "%{hiera('wso2::datasources::common::test_on_borrow')}"
    default_auto_commit : "%{hiera('wso2::datasources::common::default_auto_commit')}"
    validation_query : "%{hiera('wso2::datasources::mysql::validation_query')}"
    validation_interval : "%{hiera('wso2::datasources::common::validation_interval')}"
