CREATE TABLE IF NOT EXISTS APM_APP_HITS (
UUID VARCHAR(500) NOT NULL,
APP_NAME VARCHAR(200) NOT NULL,
VERSION VARCHAR(50),
CONTEXT VARCHAR(256) NOT NULL,
USER_ID VARCHAR(50) NOT NULL,
TENANT_ID INTEGER,
HIT_TIME TIMESTAMP NOT NULL,,
PRIMARY KEY (UUID, USER_ID, TENANT_ID, HIT_TIME),
FOREIGN KEY (UUID) REFERENCES APM_APP(UUID) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (USER_ID) REFERENCES APM_SUBSCRIBER(USER_ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE INNODB;