var schema=function(){
  return{
     name:'Permission',
     table:'permission',
     fields:[
         {
             name:'uuid'
         },
         {
             name:'bucket'
         },
         {
             name:'read'
         },
         {
             name:'write'
         },
         {
             name:'delete'
         }

     ],
    helpers:{
        find:function(context,predicate){
            context.executeQuery
        }
    }
  };
};
